### ISSUE TITLE
Lookup Results do not scroll and highlighted item does not clear if leaving input without selecting

### ISSUE THREAD

**Issue by Appfrontier** [appiphony/Strike-Components#1]
When there are scrollable lookup results and you use the arrow keys to navigate through the list of results, when you get below the break the list does not scroll. When you keep pressing the down arrow and are at the end it goes back to the first Item.

As you type and are presented with a list of results, staying in the input, press down arrow. When you get below the break, the list should scroll to the selection you are on. When you get to the end it could/should stay on the last item.

Also, When leaving the input without selection the item previously scrolled to should be cleared. Instead it is still highlighted when you reenter the input

**Comment by kevinberonilla** [comment]
Thank you for finding this bug @Appfrontier! This has been fixed in our 0.1.0 release.
