### ISSUE TITLE
Replace event.srcElement with event.target

### ISSUE THREAD

**Issue by daneowens3** [appiphony/Strike-Components#106]

**Comment by daneowens3** [comment]
this change has been made to all code containing event.srcElement

**Comment by dsharrison** [comment]
Great to hear this is getting fixed. If you guys fixed this yourselves you can decline my PR (#58) after.

**Comment by daneowens3** [comment]
@dsharrison thanks a lot for the PR and your contribution. I went and made the changes prior to viewing your code so we wont use them, but again thanks for the support!
