### ISSUE TITLE
Fix scrolling issue: multiSelectPicklist

### ISSUE THREAD

**Issue by daneowens3** [appiphony/Strike-Components#107]

**Comment by daneowens3** [comment]
a fix has been implemented for next release

**Comment by dorianbass** [comment]
Is there any chance you could publish the fix for this issue on a separate branch or something?  It's really blocking a project that I'm working on.

**Comment by daneowens3** [comment]
Dorian,

These changes were in our last release and you can get them buy updating to
the latest version of strike.

Regards,
Dane
