### ISSUE TITLE
Strike Lookup Bug

### ISSUE THREAD

**Issue by waltonzt** [appiphony/Strike-Components#117]
Every once and a while I get this bug.
```
Error in $A.getCallback() [null is not an object (evaluating 'returnValue.isSuccess')]
Callback failed: apex://inscor.strike_lookupController/ACTION$getRecords
```

I can't seem to find a reliable testing scenario. Please advise.

**Comment by daneowens3** [comment]
@waltonzt could you let me know when this happened, what you were attempting to do as I have not seen this issue nor can I reproduce it.

**Comment by waltonzt** [comment]
Thats the weird part, It pops up at random times. Sometimes when you select an option from the lookup results and sometimes it just happens when a result is selected and nothing is being done on the page. I have only ever seen this error happen in one org in which our package is installed in. We upgraded their package to a latest version since I have not seen it happen in the latest version. 

We did have to modify the `strike_lookup` js Controller with the line
```
if(!lookupMenu){
   return;  
}
```
In the `handleFocusIndexChange` function because we were getting another error when using a strike lookup on a page which is accessed from the Utility Bar. Im thinking maybe this fixed the issue as well but do not know.

**Comment by daneowens3** [comment]
unfortunately i've been unsuccessful in replicating this issue. if it arises again feel free to reopen and I will take another look.

**Comment by waltonzt** [comment]
We are having similar issues again. Our package is installed in a customers org and this error is popping up.
![capturesnip_2](https://user-images.githubusercontent.com/17326871/34742718-1a92772a-f555-11e7-9697-3c7470e90ef3.png)

This error does not show up in our org so we cant reproduce it but it is definitely showing up in their org. Do you have any advice?
