### ISSUE TITLE
Strike Select when searchable cant toggle menu

### ISSUE THREAD

**Issue by daneowens3** [appiphony/Strike-Components#122]

**Comment by daneowens3** [comment]
fixed issue with menu not opening when searchable due to blur method closings the menu when the search input is focused. if searchable blur will not close the menu until the search input is blurred.

**Comment by camisotro** [comment]
Just noticed this yesterday while trying to demo it to my project manager on the lightningstrike.io web site. However the previous day I'd loaded the components into my sandbox using Strike CLI and it was an older version than the latest commit. The older version works fine so something broke on a recent commit.

**Comment by daneowens3** [comment]
hello @camisotro we have already implemented a fix and are working to get it all tested for a patch early next week. Im sorry for the inconvenience, but I can assure you a fix will be out asap!

**Comment by camisotro** [comment]
No worries, will stick with the old version for now and go enjoy Dreamforce this week! :)

**Comment by camisotro** [comment]
Any progress on this? Thanks!

**Comment by daneowens3** [comment]
@camisotro this has been fixed in our latest release, out today. Sorry for the delay with dreamforce and then the holiday our resources were low, but all is well and ready to go!
