### ISSUE TITLE
Not all strike_rows rendered in strike_datagrid

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#131]
I'm loading a strike_datagrid (15 columns, cells of type COMPONENT with 20+ rows) but on the page there are only displayed 7. 

When I copy the produced JSON into the fiddler on http://www.lightningstrike.io/#!/strikeDataGrid more rows are display. But also not all of them.

Am I running into any limitations?

**Comment by daneowens3** [comment]
Is is possible you could send me the data json you are passing in? the 15 columns and 20+ rows?

**Comment by up2go-sschwarz** [comment]
`{"columns":[{"dataType":"COMPONENT","label":"","name":"productLabel"},{"dataType":"COMPONENT","label":"2017","name":"2017"},{"dataType":"COMPONENT","label":"2018","name":"2018"},{"dataType":"COMPONENT","label":"2019","name":"2019"},{"dataType":"COMPONENT","label":"2020","name":"2020"},{"dataType":"COMPONENT","label":"2021","name":"2021"},{"dataType":"COMPONENT","label":"2022","name":"2022"},{"dataType":"COMPONENT","label":"2023","name":"2023"},{"dataType":"COMPONENT","label":"2024","name":"2024"},{"dataType":"COMPONENT","label":"2025","name":"2025"},{"dataType":"COMPONENT","label":"2026","name":"2026"}],"rows":[{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"21504"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"24000"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"26631"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"29002"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"33347"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"38823"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"41138"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"40912"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"45540"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"50874"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Volume__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"44"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"4"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"66"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_VolumeOverride__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"666.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_TakeRate__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"103.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_Share__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Quantity__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"54","formatter":"currency"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"2","formatter":"currency"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"1","formatter":"currency"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"1","formatter":"currency"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__cur_Price__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"1629888.48","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"824.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"6798.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"3434741.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element1"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMAAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__fcur_Revenue__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"1478"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"8282"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"11836"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"13375"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"12948"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Volume__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_VolumeOverride__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_TakeRate__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_Share__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Quantity__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__cur_Price__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element2"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MEMFAA4"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__fcur_Revenue__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Volume__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_VolumeOverride__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_TakeRate__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"100.00","formatter":"percent"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__pct_Share__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"1"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__num_Quantity__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0","formatter":"currency"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__cur_Price__c"},"type":"ui:outputText"}},{"2017":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2018":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2019":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2020":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2021":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2022":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2023":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2024":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2025":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"2026":{"attributes":{"type":"number","variant":"label-hidden","value":"0.00","formatter":"currency","disabled":"true"},"type":"lightning:input"},"productLabel":{"attributes":{"value":"Element3"},"type":"ui:outputText"},"productId":{"attributes":{"value":"a0046000003MMiyAAG"},"type":"ui:outputText"},"fieldName":{"attributes":{"value":"CPRM_DM__fcur_Revenue__c"},"type":"ui:outputText"}}]}`

@daneowens3 Inserting this to the data section at http://www.lightningstrike.io/#!/strikeDataGrid will display all rows, but using it in our component, only the first 3 lines of Element2 show up.
`<c:strike_dataGrid data="{!v.grid}" />`

**Comment by dionbero** [comment]
There is a loadMoreAmount attribute on the strike_dataGrid cmp file that is meant to determine the initial amount of rows displayed as well as the amount loaded when using a “load more” button.  The default of that attribute is set to 10 but you may set it to a number that will work with your grid.  We will be adding the loadMoreAmount attribute to the fiddler as well as the ability to add a load more button.

**Comment by up2go-rsoesemann** [comment]
@dionbero very cool! Works like a charm. Thanks for pointing me to the undocumented attribute.
