### ISSUE TITLE
Popover overflows when used inside slds-table

### ISSUE THREAD

**Issue by sjurgis** [appiphony/Strike-Components#136]
I am using the popover inside a slds-table. Unfortunately the body is overflowing:

<img width="474" alt="screen shot 2017-11-15 at 2 19 21 pm" src="https://user-images.githubusercontent.com/7092409/32813707-47f6c286-ca10-11e7-80fd-f890a533ef67.png">

Will try to find some hack to prevent it.

**Comment by sjurgis** [comment]
Ok here's a fix:
          <aura:set attribute="popoverBody">
            <div style="white-space: normal;">{!v.content}</div>
          </aura:set>

**Comment by kevinberonilla** [comment]
Thanks for logging this, and for providing the workaround. We will investigate why this is happening.

**Comment by daneowens3** [comment]
ive implemented this fix and it works, thanks @sjurgis for providing a solution. we will be sure to include this in our next update!
