### ISSUE TITLE
First multiSelectPicklist always auto-opened on load

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#144]
My component contains multiple instances of `strike_multiSelectPicklist`. When the component is loaded the first of them is auto-opened because of the onFocus handler in your code.

This not only looks strange and I am unable to handle that elegantly from the outside.

**Comment by daneowens3** [comment]
are you for any reason focusing the picklist on load? i cant seem to reproduce this, it loads fine on lightning.io

**Comment by up2go-rsoesemann** [comment]
No I don't call any Javascript to focus it. This is how my markup looks

```
<aura:component implements="force:lightningQuickAction,force:hasRecordId">

    <aura:iteration items="{!v.attributes}" var="attribute">
        <div data-field="{!attribute.field}" onmouseenter="{!c.lazyloadOptions}">
            <c:strike_multiSelectPicklist value="{!attribute.valueString}" placeholder="{!attribute.label}" label="" 
                                          singleSelect="{!attribute.singleSelect}" 
                                          disabled="{!attribute.readOnly}" 
                                          error="{!and(attribute.required, empty(attribute.valueString))}"
                                          errorMessage="..."
                                          onchange="{!c.fireEvent}" 
                                          class="{!not(empty(attribute.valueString)) ? 'filtered' : ''}">
                                          
                <c:strike_option label="Loading..." value="" disabled="true" hidden="{!not(empty(attribute.options))}"/>
                
                <aura:iteration items="{!attribute.options}" var="option">
                    <c:strike_option label="{!option}" value="{!option}" destroyable="{!not(attribute.readOnly)}" />
                </aura:iteration>
            </c:strike_multiSelectPicklist>
        </div>
    </aura:iteration>
</aura:component>
```

**Comment by daneowens3** [comment]
Hello @up2go-rsoesemann i've been looking at this trying to implement as close to the way you did as I can. I see you've added your own attribute and I have no access to controller methods... Could you give me necessary javascript to pull this off? I'ts just the first one that opens? I've put many on a page with an iterator as you did and still cant get this to happen.

**Comment by up2go-sschwarz** [comment]
@daneowens3 @up2go-rsoesemann this seems to be context specific. Meaning, that Quick-actions automatically focus on their first element, but under other circumstances eg. in an `aura:application` there is no auto-focus. (Only tested with these two)

Auto Focus:
```
<aura:component implements="force:lightningQuickAction">
    <input type="text" />
</aura:component>
```
No Focus:
```
<aura:application extends="force:slds">
    <input type="text" />
</aura:application>
```

**Comment by daneowens3** [comment]
Ic, Is it auto focusing when you aren't using a quick action? I don't have control over the quick action behavior, the component will only open of focus.

**Comment by up2go-rsoesemann** [comment]
No it's not opening when used elsewhere. I guess you are right this is not a Strike issue. And as focusing the first form element is also a best UX practice I guess we have to find a custom solution.
