### ISSUE TITLE
Bad performance when removing pills from multiSelectPicklist

### ISSUE THREAD

**Issue by up2go-sschwarz** [appiphony/Strike-Components#146]
We are using the `c:strike_multiSelectPicklist` with 0 to 100 select options.
The more options we have, the slower does it render, when we remove an option pill from the selected values. I was able to speed it up with commenting out the doSearch method. I guess there are things happening, that are slowing down the performance (about 1-2 seconds).
```
handleComponentDestroyed: function(component, event, helper) {
    ...
    //helper.doSearch(component, event, helper, component.get('v.searchTerm'), component);
    ...
},
```

**Comment by daneowens3** [comment]
removing doSearch will break scrolling via keyboard. I have to do more research on how to remedy this issue, but as a fyi commenting doSearch will mess up keyboard scrolling as it filters out selected options from unselected so your list scrolls properly.
