### ISSUE TITLE
Multipicklist duplicates value data on refresh

### ISSUE THREAD

**Issue by TomSesselmann** [appiphony/Strike-Components#15]
The `helper.handleValueOnInit` function calls `child.strike_optionSelected()` on each pre-populated option which then sends out a `"strike_evt_notifyParent"` which then calls `helper.addToComponentValue()` which adds a new value on to the existing value array.

So you end up with "option-1;option-1" and if you save that data and refresh again you'll get "option-1;option-1;option-1"

I'm running Release 0.1.0 at the moment but I couldn't see a fix in the changelog.

**Comment by kevinberonilla** [comment]
@chewy2 or @trentchilders Do any of you have a solution for this issue?

**Comment by TomSesselmann** [comment]
For now, I've just added a quick check before it pushes the duplicate value on to the array.
I'm assuming all the values are unique and there should never be duplicates in the array.
```
        if (valueArray.indexOf(selectedOptionValue) == -1) { 
            valueArray.push(selectedOptionValue);
        }
```

**Comment by kevinberonilla** [comment]
Hi @TomSesselmann, that definitely works. We haven't been able to pinpoint the issue yet on our end. How are you saving the data?

**Comment by TomSesselmann** [comment]
It's bound to the field using value="{!v....}" and then saved to Salesforce via an APEX upsert

**Comment by TomSesselmann** [comment]
Just updated to 0.6 from 0.1 and still seeing the issue.

If you put a `console.log(newValue);` at the end of the `addToComponentValue` function in `strike_multiSelectPicklistHelper.js` then create a new component like this

```
<c:strike_multiSelectPicklist
    value="option1;option2" >
    <c:strike_option label="option1" value="option1"/>
    <c:strike_option label="option2" value="option2"/>
</c:strike_multiSelectPicklist>                           
```

You should see `option1;option2;option1;option2` in the console

**Comment by kevinberonilla** [comment]
Thanks for the update. Our 0.6.0 release was mainly for two new components that have been in the works for quite some time and we decided they were due for a release. It didn't contain many bug fixes.

We will look into this issue for the next patch release.

**Comment by kevinberonilla** [comment]
@TomSesselmann We're looking into an issue that we ran into with Multi Select Picklist and found what could be the cause of your issue. If you open the component's helper file (`strike_multiSelectPicklistHelper.js`) and change the following line (line 8)
```
valueArray.push(selectedOptionValue);
```
to
```
if (valueArray.indexOf(selectedOptionValue) == -1) {
    valueArray.push(selectedOptionValue);
}
```

This change could fix your issue. Please let us know if this helps!

**Comment by TomSesselmann** [comment]
That's the same change that I already suggested above 😛 
Yep, that fixes the issue.

**Comment by kevinberonilla** [comment]
Ahh sorry, you're right! Running into it ourselves reminded me that this issue was still open. I wanted to give you an update. Thanks!

**Comment by up2go-rsoesemann** [comment]
@kevinberonilla We also ran into this. In September ;-). Is this still in testing because the suggested fix doesn't work? Is there an estimate when you are going to release the fix?

**Comment by mikeblazek** [comment]
@up2go-rsoesemann at the moment we do not have an estimate on when we will get another release out.   We had believed this was no longer an issue.  We currently have a lot of project work, so we will not be able to get back to this for a few weeks.

**Comment by lulzimfazlija** [comment]
@TomSesselmann great job, I was also having same issue, luckily it was u that found out. out of curiosity, how did u find out that addToComponentValue was called, or strike_evt_notifyParent is fired. Can u explain a bit!
