### ISSUE TITLE
Multiselect Picklist options are rendered wrong when there is an error message

### ISSUE THREAD

**Issue by up2go-sschwarz** [appiphony/Strike-Components#150]
![screenshot 2017-11-24 17 44 40](https://user-images.githubusercontent.com/12232063/33218875-915d5904-d13f-11e7-8225-6661d99af2e4.png)

Pull Request will come soon.

**Comment by burhan7** [comment]
@up2go-sschwarz Thank you for the pull request. We'll merge it to the master branch and it'll be part of the new release. We appreciate your contribution.
