### ISSUE TITLE
multipicklist deselecting pill bug

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#156]
There is an bug on multipicklist component, whenever I deselect one pill (pressing "X") I get thrown on the top of the page if not already at top.

**Comment by daneowens3** [comment]
thanks @matejp84 for logging this bug, i too am seeing the same thing and will investigate further as to why this is happening

**Comment by daneowens3** [comment]
@matejp84 so it appears no scroll position was set on destroy thus scrolling back to the origin. i set the position to current position so it will not longer scroll the window when destroying a pill. expect to see this change in our next release. thanks!

**Comment by matejp84** [comment]
Any date when we can expect next release? :)

**Comment by matejp84** [comment]
I will write here as it is related bug. Today I found out, that on same component, when user tries to write into input, whole page just scroll to top. Probably related thing? If not, I will open new issue.
