### ISSUE TITLE
Warning message "moment construction falls back to js Date" in date picker

### ISSUE THREAD

**Issue by shamina-mossodeea-sc** [appiphony/Strike-Components#16]
The following deprecation warning message is reported in Chrome console when selecting a date in date picker:

`Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
       at AuraLocalizationService.$formatDate$ (..../auraFW/javascript/ZCuyRUYzK_kAf4cKCIeS2A/aura_proddebug.js:15280:15)
    at clickDate (..../components/c/strike_datepicker.js:160:59)`

**Comment by kevinberonilla** [comment]
Thanks for logging this! We will need to reformat the use of the `moment` constructor. Removal of this warning will be part of the next release.

**Comment by kevinberonilla** [comment]
Thanks for logging this! After some investigation, it seems this warning stems from the Salesforce end as the datepicker itself does not use the `moment` constructor directly, but instead uses the `$A.localizationService` object (https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/components_l10n.htm).

We will notify the Salesforce engineers of this warning.
