### ISSUE TITLE
Strike Data Grid should control 'Load More' button visibility on data change

### ISSUE THREAD

**Issue by kevinberonilla** [appiphony/Strike-Components#163]
A change handler can be added to the data attribute that runs logic to set the proper `v.showLoadMore` value. This is currently only an issue if a table initially has more than 10 rows (or whatever `v.loadMoreAmount` is set to), and then changes to have less rows than that. The 'Load More' button still appears in that situation.

Also, there's no space in the button text; should be 'Load More' not 'LoadMore.'
![screen shot 2017-11-30 at 10 55 25 am](https://user-images.githubusercontent.com/8738640/33443516-63ce0b5a-d5bd-11e7-869c-78f54aa7f3e1.png)

**Comment by daneowens3** [comment]
I've added a fix so the button is handled more intuitively and added a space to the button's label. Will reflect in next release
