### ISSUE TITLE
Multiselect Picklist error in FF 45.7.0 ESR

### ISSUE THREAD

**Issue by up2go-sschwarz** [appiphony/Strike-Components#164]
Some of our customers are using FF 45.7.0 ESR ([Windows](http://download.mozilla.org/?product=firefox-45.7.0esr-SSL&os=win&lang=de), [Mac](http://download.mozilla.org/?product=firefox-45.7.0esr-SSL&os=osx&lang=de))
And whenever they do one of the following actions:
1. Enter a search term
2. Delete a pill

Line 252 throws this error message:

> TypeError: Action failed: CPRM_DM:strike_multiSelectPicklist$controller$handleComponentDestroyed [childCmps is undefined]

```
249: var childCmps = component.get('v.validChildCmps');
250: component.set('v.validChildCmps', null);
251:
252: for (var i = 0; i < childCmps.length; i++) {
```

**Comment by daneowens3** [comment]
the latest version of FF ESR is 52.5.0, is there a reason they are on an old version? I don't get any errors on 52.5.0. perhaps they need to update?

**Comment by up2go-sschwarz** [comment]
Valid question. Customers... :)
