### ISSUE TITLE
multiselect picklist fails on VF page

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#165]
I have put my final LEX component which is using strike-multiselect picklist on VF page as customer is not ready yet to full switch to LEX. 
I get the following error: 
This page has an error. You might just need to refresh it. Action failed: c:strike_multiSelectPicklist$controller$externalValueChange [null is not an object (evaluating 'inputField.getElement().value = ''')]
inputField is properly found and evaluated, but when calling getElement on it it return null, but only if component is on VF page, in LEX it works properly. 
Is there anything I should be aware using this component? 
Also if I comment out that line next error is thrown in handleNotifyParent and component is useless in that case.

**Comment by daneowens3** [comment]
@matejp84 i am able to add the component to a VF page w/o any errors. Are you using the latest version? have you made any changes to the component?

**Comment by matejp84** [comment]
No no changes, using 0.10.1 version.
This is html code where I use the component:
`<c:strike_multiSelectPicklist label="Contract status:" aura:id="status" value="{!v.filters.statuses}">
                                    <aura:iteration items="{!v.contractStatusPicks}" var="status">
                                        <c:strike_option label="{!status.label}" value="{!status.id}"/>
                                    </aura:iteration>
                                </c:strike_multiSelectPicklist>`
In LEX it works normally, but when component is added to VF page it throws:
This page has an error. You might just need to refresh it. Action failed: c:strike_multiSelectPicklist$controller$externalValueChange [null is not an object (evaluating 'inputField.getElement().value = ''')] Callback failed: apex://ContractSearchCtrl/ACTION$getPicklists Failing descriptor: {c:strike_multiSelectPicklist$controller$externalValueChange}
JS function that fill data and set external value is:
`
getPicks: function (cmp, event) {
        var action = cmp.get("c.getPicklists");

        action.setAbortable();

        action.setCallback(this, function (response) {
            var state = response.getState();
            if (cmp.isValid() && state === "SUCCESS")
            {
                var result = response.getReturnValue();
                console.log(result);
                cmp.set("v.contractStatusPicks", result.contractStatus);
                cmp.set("v.agreementTypePicks", result.agreementType);

                let mode = cmp.get("v.mode");

                if(mode === "coordinator")
                {
                    cmp.find("status").externalValueChange('New');
                }
                else
                {
                    cmp.find("status").externalValueChange('Valid and Active');
                }
            }
            else if (state === "ERROR") // Handle any error by reporting it
            {
                var errors = response.getError();

                if (errors)
                {
                    if (errors[0] && errors[0].message)
                    {
                        this.displayToast('Error', errors[0].message, "error", cmp);
                    }
                }
                else
                {
                    this.displayToast('Error', 'Unknown error.', "error", cmp);
                }
            }
        });

        $A.enqueueAction(action);
    }
`

**Comment by daneowens3** [comment]
@matejp84 Im guessing it has to do with this method you've created..you're passing in 'New' and 'Valid and Active' into externalValueChange. what does this do? the method accepts component, event, and helper.

**Comment by matejp84** [comment]
I should preselect an item from dropdown, and in documentation there is this for externalValueChange methond:
This method can be called in order to set the value from a source other than the strike_multiSelectPicklist itself. It accepts one parameter as a semi-colon separated string that must contain values represented in the available, nested strike_option components' values. Invalid values will be removed from the string prior to setting the value of the strike_multiSelectPicklist.

So far as I understand I can send in that method also a string with values from options in dropdown as semi-colon separated string?

**Comment by matejp84** [comment]
I have found the source of the problem, it seems that someone has put component call inside wrapping app that is also used in VF page to contain component so there was double init and in init from app component failed to get DOM element.

**Comment by daneowens3** [comment]
glad you were able to resolve this, ill close the issue for now if all is well. Things should be good in terms of strike. feel free to reopen if you run into more issues.
