### ISSUE TITLE
[Performance degradation] console log warning message on strike_lookup component

### ISSUE THREAD

**Issue by karthikkornalies** [appiphony/Strike-Components#166]
Have anyone have a workaround for the performance degradation warning for strike_lookups.

[Performance degradation] markup://aura:if ["158:208;a"] in c:strike_lookup ["148:208;a"] needed to clear unrendered body.
More info: https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/perf_warnings_if.htm
Component hierarchy:

**Comment by daneowens3** [comment]
@karthikkornalies when do you get this error? trying to reproduce this

**Comment by karthikkornalies** [comment]
Above warning occurs during the component load.  Any thoughts/workaround to fix it.

**Comment by karthikkornalies** [comment]
Has this been already fixed on the recent release?

**Comment by daneowens3** [comment]
@karthikkornalies I am unable to reproduce this error in any instance, if you are not on the latest version of strike of recommend you update your components. If you are still having trouble feel free to attach a screenshot or further explain the steps to produce the error.

**Comment by PavloShchur** [comment]
I have the same.
