### ISSUE TITLE
Add support for progress indicator component

### ISSUE THREAD

**Issue by dsharrison** [appiphony/Strike-Components#17]
This is an enhancement request to support the progress indicator component (https://lightningdesignsystem.com/components/progress-indicator).

I will open a PR to add this component and you can bring it in if it lines up with where you are headed with Strike.

**Comment by kevinberonilla** [comment]
Thanks for the PR! We will review when we can, however I should bring up that we have been working on something similar already; yours may be considered a variant of a bigger component.

Depending on the direction in which ours goes, we may or may not merge this in. There could be a chance we borrow pieces of it as well. In any case, we appreciate this contribution.

**Comment by dsharrison** [comment]
@kevinberonilla No worries, putting this together allowed me to find and fix a few bugs in our use of it as well, so no time wasted if it doesn't make it in. I am excited to see a great community project helping fill the (numerous) gaps in what is provided with Lightning Components out of the box.

**Comment by chadevanssf** [comment]
I would like to second the inclusion of this component, since SLDS seems to have deprecated the Wizard variant of progress indicator and made it the proper Path component.

**Comment by DouglasCAyers** [comment]
Really enjoying the strike components, and I believe **progress indicator** would make a great addition. Thanks!

**Comment by dsharrison** [comment]
Looks like this is going to be available in Winter '18 using the `lightning:progressIndicator` component.

**Comment by daneowens3** [comment]
thanks for the heads up!
