### ISSUE TITLE
Nested Strike Lookup in Data Table

### ISSUE THREAD

**Issue by waltonzt** [appiphony/Strike-Components#177]
I am trying to use a strike lookup in a data table but the panel with the results does not show up. Any ideas how I can make this work?

**Comment by daneowens3** [comment]
is this in reference to the data table released in winter 18? ill will try to do this and see what i get

**Comment by waltonzt** [comment]
I was just using it in a table using slds classes https://www.lightningdesignsystem.com/components/data-tables

**Comment by daneowens3** [comment]
@waltonzt i threw a lookup in a table just to see and maybe i'm not understanding the question correctly but I got this as a result 
<img width="400" alt="lookup in datatable" src="https://user-images.githubusercontent.com/29711534/34528507-c18a4846-f06e-11e7-8441-e028d515062c.png">

**Comment by waltonzt** [comment]
Hmm is it just an HTML table with slds styling? Maybe its an issue with my table

**Comment by daneowens3** [comment]
yeah i just took slds example and plugged in the lookup, perhaps it's your table.

**Comment by daneowens3** [comment]
closing this issue for now if there are no further questions. If you have more trouble feel free to reopen this issue

**Comment by waltonzt** [comment]
Thanks, I got moved to working on something else but will try messing with the table to make it work when I get back to this.

**Comment by waltonzt** [comment]
I figured out the issue was because I put the component inside a div with the class `slds-truncate`

**Comment by daneowens3** [comment]
ahh, glad you were able to troubleshoot it, good catch. best of luck feel free to reach out again if you're ever stuck
