### ISSUE TITLE
How can I make a strike_popover open onClick instead of onHover?

### ISSUE THREAD

**Issue by rsoesemann** [appiphony/Strike-Components#192]
It's cool to have popovers that open on mouseover and close on mouseout. But for those that can only be closed by clicking X there should be an option to open them on click. Otherwise the user moves over the screen and multiple popovers open and overlap without ever closing.

Could you add an option or does this already exist?

**Comment by acpolatkan** [comment]
I am having a similar situation here. Is there an option to display the popover dialog `onClick`? I just want to display the popover on demand, when the users clicks on it.

**Comment by acpolatkan** [comment]
I solved the issue on my own :) using pure css.

**myComponent.cmp**
```
    <div id="container" onclick="{!c.open}" >
        <div id="curtain"> </div>
        <div>
            <c:strike_popover >
            </c:strike_popover>
        </div> 
    </div> 
```

**myComponent.css**
```
    .THIS #container {
       width: 20px;
       height: 20px;
       position: relative;
    }

    .THIS #curtain {
       width: 100%;
       height: 100%;
       position: absolute;
       top: 0;
       left: 0;
       z-index: 10;
    }
```

**myComponentController.js**
```
   open: function(cmp, evt, helper) {
        var curtain = document.getElementById("curtain")
        curtain.style.zIndex = 0;

        setTimeout(function() {
            curtain.style.zIndex = 10;
        },100);
    },
```

**Comment by rsoesemann** [comment]
Love this solution. Thanks for sharing.
