### ISSUE TITLE
Input helpText is hidden by modal boundaries 

### ISSUE THREAD

**Issue by TomSesselmann** [appiphony/Strike-Components#20]
Hey guys, I know you can change the placement attribute of a Strike Tooltip, but how would I change it for the Strike Input helpText?

Or maybe the tooltip should just appear on top of everything.

<img width="703" alt="screen shot 2017-05-09 at 1 57 04 pm" src="https://cloud.githubusercontent.com/assets/23013276/25835120/ad58cc82-34bf-11e7-9725-1805961ce7f7.png">
<img width="678" alt="screen shot 2017-05-09 at 1 56 55 pm" src="https://cloud.githubusercontent.com/assets/23013276/25835119/ad575190-34bf-11e7-80c0-8c17c1427c2e.png">

**Comment by kevinberonilla** [comment]
We have plans to expose `strike_tooltip`'s `placement` attribute on all form elements with `helpText` available (perhaps called `helpTextPlacement`), which may not be available for some time.

For now you have a few options: you can edit `strike_input` and/or `strike_textarea` and find the line where it calls `<c:strike_input/>` to hardcode a `placement` attribute, expose your own `helpTextPlacement` attribute that receives the `placement` value from the parent (with a default of `'top'`), or you can add the `.slds-is-expanded` CSS class on the modal body's container to set `overflow: visible;`.
