### ISSUE TITLE
Support auto/fallback positioning for popovers

### ISSUE THREAD

**Issue by dsharrison** [appiphony/Strike-Components#21]
When supplying a position for a popover, the popover may be stretch outside the document body. Bootstrap handles this with an "auto" placement option that will swap the placement if your preferred placement does not have space (http://getbootstrap.com/javascript/#popovers-options). It would be great for the Strike Popover to support this same (familiar) "auto" syntax.

With this implemented, a popover of position "auto top" that would stretch off the top of the page would instead be positioned below.

**Comment by kevinberonilla** [comment]
I think we can implement this, though there would have to be some testing with Locker Service. Great suggestion nonetheless.

**Comment by dsharrison** [comment]
We had an immediate need for this so our team came up with an approach that is LockerService friendly. Would you like a PR to be opened to bring the changes back into the main project?

**Comment by kevinberonilla** [comment]
A PR would be appreciated! Feel free to create one and we can review it.
