### ISSUE TITLE
strike_svg broken in Summer 18

### ISSUE THREAD

**Issue by camisotro** [appiphony/Strike-Components#220]
It would seem that, in a Summer 18 pre-release org, even when a component and all the Strike components are set to an API version of 40/41/42, strike_svg no longer works properly.

Minimal example:
In a Summer 18 org, install **strike_picklist** and create a component that contains a **strike_picklist** with **searchable="true"**. Notice that when searching, the magnifying glass icon (presently implemented via strike_svg) does not appear. Compare with a Spring 18 org in which it does appear. If you investigate with Inspect Element you'll see the SVG tag was created, and the USE tag was created, but the xlink:href attribute was never added.

While I understand that for the most part strike_svg can now be refactored to lightning:icon, there are some cases where it doesn't do the job. Namely, the class attribute of lightning:icon only applies classes to the wrapping container and not to the SVG tag itself. Certain SLDS constructions require classes on both the wrapper and the SVG tag. So I borrowed the strike_svg code for some components of my own to act accordingly. Unfortunately once the sandbox in question upgraded to Summer18 the icons didn't appear anymore.

I could raise this to Salesforce myself but it would probably be more influential coming from Appiphony. :)

**Comment by kevinberonilla** [comment]
Hi @camisotro, we are aware of this change and will be phasing out use of `strike_svg` in all future releases to comply with the release's needs. A refactor will need to be done on all cases that can be replaced with `lightning:icon`, but unfortunately this means we will need to drop custom icon/image functionality in multiple components.

**Comment by camisotro** [comment]
FYI, I got a response from SFDC on this at StackExchange:
https://salesforce.stackexchange.com/questions/217837/summer-18-svg-blocked-in-lightning-components?noredirect=1#comment330428_217837
_Locker Service team has been notified of this issue with SVG elements using href attribute in Summer 18. We are working on a resolution. If you file a customer case, please reference this investigation W-4981475_ – **Ravi Jayaramappa**

**Comment by kevinberonilla** [comment]
Thanks for the update! We'll closely monitor this issue internally ourselves as well. Hopefully they will continue to allow use of that attribute so we can keep our custom icons.

**Comment by camisotro** [comment]
Yeah hoping they pull through on this.

Also notable: Summer 18 introduces support for **lightning:icon** taking a custom **src** attribute. That might help. But it still remains that **lightning:icon** can only apply a class to the wrapping element and not the svg tag itself.

**Comment by camisotro** [comment]
It looks like Salesforce did indeed solve this in time for release. However some icons still aren't showing up. I think it might be because of the hard-coded URL. For example strike_picklist references "/resource/icons/utility-sprite/svg/symbols.svg#search" which is not working. But if I change it to "/apexpages/slds/latest/assets/icons/utility-sprite/svg/symbols.svg#search" I get the search icon back.

**Comment by georgekenessey** [comment]
Since we are no longer supporting this project I am closing this issue.
