### ISSUE TITLE
Add strike_inputField component

### ISSUE THREAD

**Issue by dsharrison** [appiphony/Strike-Components#24]
When working with sObjects, using the traditional `<apex:inputField />` component gives an enormous benefit as it renders an input that leverages admin customizations to the field. This also simplifies markup and makes dynamic markup a lot easier. Salesforce tried to add this with the lightning `<force:inputField />` but as I am sure you are aware, this component has been riddled with issues since release and is basically unusable.

Is the Strike team considering or already working on wrapping a bunch of their awesome new components into a `<c:strike_inputField />` component? There is one huge limitation when compared to the standard `<force:inputField />` and that is that I am not aware of a way to determine sObject name and field name from just the primitive value passed in. However, our team believes that even if we have to initialize an input field like `<c:strike_inputField value="{!v.record.MyField__c}" sObjectName="Account" fieldName="MyField__c" />` this would still be a hugely beneficial component.

 As a side note we do have a base for this in our own components and if this is something that the strike team is interested in adding and is not already under active development I would be happy to share what we use.

**Comment by lfreeland** [comment]
I'm very interested in this too and would hate to create something that is in active development. I'd be happy to collaborate on a base component that exists already.

**Comment by mikeblazek** [comment]
@lfreeland @dsharrison 

We are potentially working on new components and I am wondering what features this component would need to support to be useful.  Perhaps a sub set of the types out there would be a good starting point.  Any feedback will help determine if we can take this on at this point.

**Comment by lfreeland** [comment]
@mikeblazek,

At a high-level, I'd love to have the lightning equivalent of the Visualforce <apex:inputField> where, as @dsharrison pointed out, we could give it the object and field as input and it would dynamically render the appropriate label and input field type based on the field's underlying data type. It would be really nice if it took into account the user's field level security too. Implementing this would be a tall order so even starting with a subset of supported types already implemented would be good.

**Other Desirable Features**
- Automatic Required Field Detection. Based on the field definition, automatically require it if it's a required field.
- Required Setting. Allow one to set an attribute to specify if the field is required or not. This would override the Automatic Required Field.
- Styling Setting(s). Being able to pass in class names and perhaps inline styling.
- Allow Common Event Handlers such as onclick, onkeypress, etc.
- Allow one to specify the label in case the field's label should be overridden.

**Comment by dsharrison** [comment]
+1 to everything @lfreeland said there. The only thing I have to add from our implementation is that we added the ability to control the display of the field label with the following options:

- Default
- Hidden
- Heading Small
- Heading Medium
- Heading Large

This allows the inputs to be used more effectively in a community or other site where matching the internal Salesforce styling isn't as important as making an appealing and easy-to-use UI for people not familiar with Salesforce.

**Comment by dsharrison** [comment]
If I have some time over the next few days I will put a gist together with some pseudo-code outlining what we are doing.

**Comment by lfreeland** [comment]
The [Lightning Base Components Roadmap](https://help.salesforce.com/articleView?id=lightning_components_roadmap.htm) says that Salesforce is releasing an inputField Lightning base component in Winter 18 so that'll be interesting to see what they release. May be worth waiting to see what it's like in the preview in the coming weeks before trying to implement it here.

@dsharrison @mikeblazek

**Comment by dsharrison** [comment]
Oh this will be great if Salesforce actually implements it. They are missing a bunch of the building blocks that the Strike team has implemented here though (for example Lookup - a fundamental component for interacting with Salesforce relationship fields) so I am curious as to what they are going to deliver.

**Comment by lfreeland** [comment]
Hey guys. Last night I was playing around with creating a Field Set Form that generates a bare bones, one column form that lets one insert or update a record. The set of fields shown on the form are driven by a specified field set. [Field Set Form](http://metillium.com/2017/08/lightning-field-set-form-component/)

To create an inputField component, there would probably be a lot of similar overlapping code so I thought it could be used as a starting point, if needed. As @dsharrison pointed out, we'll have to see what the Salesforce inputField functionality looks like first.

Also, thanks for the wonderful library. It's greatly benefited me and my client.

**Comment by daneowens3** [comment]
This is a component we may consider building in the future, but there are no plans at the moment for this component.
