### ISSUE TITLE
strike_multiSelectPicklist Causing warning in Locker Service

### ISSUE THREAD

**Issue by chadevanssf** [appiphony/Strike-Components#25]
For a Summer '17 release, I am seeing this warning in the output:

Unsupported SecureComponent: markup://c:strike_pill {488:0}{ key: {"namespace":"c"} } method: Symbol(Symbol.isConcatSpreadable). Returning undefined

It is being caused by line 45 of the helper:

component.set('v.selectedOptionPills', [].concat(selectedOptionPills));

Changing to this line fixes the warning:

component.set('v.selectedOptionPills', Array.prototype.concat.apply([], selectedOptionPills));

**Comment by kevinberonilla** [comment]
Thanks for bringing this up! We'll be sure to include this update for the next release.
