### ISSUE TITLE
Add BSD 2-Clause License to All Files

### ISSUE THREAD

**Issue by kacrouse** [appiphony/Strike-Components#29]
It would be extremely helpful if the copyright, license conditions, and license disclaimer were included in all source code files so that those using these components are compliant with the license by default. Otherwise, to be compliant, one has to go through each file and add in the license.

**Comment by kevinberonilla** [comment]
Great idea! We are already planning to include commented information like
version numbers in each file and this would be a good addition. Thanks for
the heads up!
