### ISSUE TITLE
"Layout & Layout Item" live code example fails in Summer '17

### ISSUE THREAD

**Issue by gotoplanb** [appiphony/Strike-Components#31]
If I copy/paste the [live code sample](http://www.lightningstrike.io/#!/layout) into a new Lightning component, I get a FAILED_INTEGRITY_EXCEPTION error when trying to save. Full message:

```
Failed to save undefined: 0AdK00000008gXL:7,5: ParseError at [row,col]:[8,5] Message: Element type "lightning:layout" must be followed by either attribute specifications, ">" or "/>".: Source
```

There is a missing angled bracket. 

If I replace:

```
<lightning:layout
    horizontalAlign="center"
    verticalAlign="start"
    pullToBoundary="small"
    <lightning:layoutItem
```

with:

```
<lightning:layout
    horizontalAlign="center"
    verticalAlign="start"
    pullToBoundary="small">
    <lightning:layoutItem
```

then I can save, and the component loads as expected.

I looked for a file in this repo that manage the live code samples, but I don't find it. So, I humbly submit this issue instead of making a PR myself.

**Comment by kevinberonilla** [comment]
Good catch, thanks for logging this!

**Comment by LavanyaNair604** [comment]
I was going through this error and found this link thanks! :)
