### ISSUE TITLE
Reseting binded value of Multiselect picklist from another component doesn't rerender Strike Multiselect

### ISSUE THREAD

**Issue by DirtyWork** [appiphony/Strike-Components#33]
When I have binded an attribute to a Strike Multiselect picklist and I'm resetting the value of that attribute outside of Multiselect (eg. in the parent component) then the Strike Multiselect component wont automatically get re-rendered.

This works fine with Strike Lookup component.

**Comment by kevinberonilla** [comment]
Just FYI, we've exposed an Aura method named `externalValueChange` that can be called on the component to rebuild the selections. This will be added and documented in our next release, which will be coming soon.
