### ISSUE TITLE
on change events

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#36]
As it seems, there is no on-change events on lookup components fired, so is there any option that this will be added in future releases?

**Comment by matejp84** [comment]
Also would be nice to have onchange on datepicker component as well.

**Comment by kevinberonilla** [comment]
Hi @matejp84,

Thanks for suggesting this! We'll see if we can sneak this into the next release, which is a smaller one in terms of Strike Component updates. Otherwise this should definitely be available in a future update.

**Comment by matejp84** [comment]
Is there any ETA when we can expect new version? I'm kinda tight on schedule to implement things for our customer and deadline is by 24.7. 
Would be nice to know, if I can wait or just implement my own solution for time being and after update switch to yours events. :)

**Comment by mikeblazek** [comment]
@matejp84 I would suggest implementing it yourself and submitting a pull request to us.  We love to have to community contribute to our project.   

Our release should be coming out next week but no guarantees on what will be included or not.
