### ISSUE TITLE
bug in strike_input

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#37]
There is and typo in attribute name "tabIndex" in strike_input component. Today I created few datepickers and got exceptions that tabIndex is not visible to strike_input, then I searched through the code and discovered, that attribute in strike_input is actually written with lower case "tabindex". Looks like attribute names are now case sensitive.

**Comment by burhan7** [comment]
Thanks for logging this, @matejp84 
It'll be fixed in the new release

**Comment by matejp84** [comment]
Found another bug in strike_input,
when using is as checkbox, in safari checked value is reverted - logic works reversed as in chrome and other browsers. 
I'm using event.getSource().get("v.checked"); to get checked value when event is fired when listening for all strike_evt onchange events (checking multiple checkboxes).
