### ISSUE TITLE
Exception in handleOnblur function in multiSelectPicklist in firefox

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#39]
I'm getting an exception that srcElement is not defined when opening and closing multiSelectPicklist dropdown menu in firefox. In other browsers seems to work ok.

**Comment by dsharrison** [comment]
`Event.srcElement` is indeed [non-standard](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement). `Event.target` should likely be used instead in [the controller function](https://github.com/appiphony/Strike-Components/blob/master/aura/strike_multiSelectPicklist/strike_multiSelectPicklistController.js#L72). You can probably try this small update directly in your copy of the component to confirm the fix.

**Comment by matejp84** [comment]
Yes this fix works ok in Firefox, Safari and Chrome. Didn't tested in IE yet.

**Comment by matejp84** [comment]
Ok this fixed the error, but I get next error on strike_lookup component not, when embedding whole component/app to VF page:

This page has an error. You might just need to refresh it. Action failed: c:strike_lookup$controller$handleFocusIndexChange [null is not an object (evaluating 'lookupMenu.getElementsByTagName')] Failing descriptor: {c:strike_lookup$controller$handleFocusIndexChange}

Sometimes error is visible directly after page is loaded, sometimes I have to click trough all lookups and picklists for error to show, but no error is thrown if I open everything directly in LEX.

**Comment by dsharrison** [comment]
If you are getting a different issue on a different component you should open a new issue.

**Comment by daneowens3** [comment]
we will implement this change in our next release

**Comment by up2go-sschwarz** [comment]
@daneowens3 can you already give a hint when the next release will be published?

**Comment by kevinberonilla** [comment]
@up2go-sschwarz right now it's hard to say. My best guess is that an official release may not surface for a few weeks. A majority of our dev and QA resources are swamped with client work, and the Winter release introduced new bugs that must be fixed as part of our next version so our to do list doubled in size.

The good news is we've already crafted fixes for a majority of the Winter bugs in our client work. Bringing them back to Strike will expedite things, assuming QA gives us the okay.
