### ISSUE TITLE
Microsoft edge browser. strike_multiSelectPicklist blur issue. 

### ISSUE THREAD

**Issue by dirajkumar** [appiphony/Strike-Components#40]
When you have more options, the scroll bar is automatically added by the edge browser and when clicked on it the options disappear.

![edge issue](https://user-images.githubusercontent.com/1153390/28430544-ecbed610-6d4e-11e7-897f-710a28965ab6.gif)

**Comment by kevinberonilla** [comment]
Hi @dirajkumar,

Thank you for logging this! We're having an issue replicating this on our end (it could just be our test environment). Do you happen to be using the latest version of the component (0.7.0)? We will continue to investigate in the meantime.

**Comment by justinAppiphony** [comment]
@dirajkumar I have not been able to duplicate this on Edge. Also, wondering the same as Kevin. Thank you,
Justin Thornton
