### ISSUE TITLE
error thrown on strike_lookup component when embedded in VF page.

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#48]
I get next error on strike_lookup component not, when embedding whole component/app to VF page:

This page has an error. You might just need to refresh it. Action failed: c:strike_lookup$controller$handleFocusIndexChange [null is not an object (evaluating 'lookupMenu.getElementsByTagName')] Failing descriptor: {c:strike_lookup$controller$handleFocusIndexChange}

Sometimes error is visible directly after page is loaded, sometimes I have to click trough all lookups and picklists for error to show, but no error is thrown if I open everything directly in LEX.

**Comment by trentchilders** [comment]
Hi @matejp84 Thanks for logging this bug. I'm having a hard time reproducing the error that you are getting.  http://lightningstrike.io is actually created on a visualforce page and I don't see the error there. Just to make sure, I made a new vf page and rendered the strike_lookup component on it like this:
```
<apex:page>
<apex:includeLightning/>
<div id="comp"></div>
<script>
	$Lightning.use("c:myApp", function () {
	    $Lightning.createComponent("c:strike_lookup", {"object": 'Account', 'searchField': 'Name'}, 
             "comp", function (cmp) {
	               console.log('loaded');
	    });
	});
</script>
</apex:page>
```

And this seemed to work fine for me. Can you share your code how you implemented this so that I can debug?

Thanks!

**Comment by matejp84** [comment]
Ok here is the code of page:

`<apex:page id="DOR_Details_LEX" standardStylesheets="false" docType="html-5.0" applyBodyTag="false" applyHtmlTag="false" showHeader="false" sideBar="false">

    <apex:includeLightning />

    <div id="lightning"></div>


    <script>
        //DORDetailsApp
        $Lightning.use("c:DORDetailsApp", function () {
            $Lightning.createComponent("c:DORDetailsCmp", {}, "lightning", function (cmp) {

            });
        });
    </script>
</apex:page>`

here is usage of strike_lookup inside my component:
`<c:strike_lookup label="Dealer" placeholder="Search dealers" searchField="Name" object="Dealer__c" aura:id="dealerLookup" strike_change="{!c.strikeChanged}" class="strike-element" required="true" errorMessage="Dealer is required." error="{!v.dealerError}"/>`

**Comment by trentchilders** [comment]
I tried running this as you've indicated above and I still am not getting the error on my end. This time I created a wrapper component and pasted in your component code with the following differences: changed `Dealer__c` to `Account`, removed `strike_change`, removed `error`. What do `strike_change` and `c.strikeChanged` do? Is this something you've added to the controller? If so, it could be interfering with something. Maybe you could remove that attribute and test to see if you still get the error. Other than that make sure you are using the most up to date versions of the components. If that doesn't help, you may have to stick with your try/catch solution for now.

**Comment by matejp84** [comment]
Right, I modified lookup component a bit, to get onChange event when value of component is changed, what I have done: 

registering new event inside component:
`<aura:registerEvent name="strike_change" type="c:strike_evt" description="Fires when value of component changes" />`

added two lines of code inside handleValueChange function of component js controller:
`var changeEvent = component.getEvent("strike_change");
        changeEvent.fire();`

Would that interfere with handleFocusIndexChange function? I can try also with comment out the code and rerun, but I really need onChange event on all available components, because sometimes I have to put additional logic on that event to verify input and also enable/disable other components depending on selected value.

**Comment by trentchilders** [comment]
I added the onchange handler as you specified to test this and I still can't get the error.

**Comment by trentchilders** [comment]
I copied your code into my org exactly and I'm still not getting the error. I can't figure out why you are getting it and I am not.
