### ISSUE TITLE
strike_modal not removing event listener 'transitionend' 

### ISSUE THREAD

**Issue by rueni** [appiphony/Strike-Components#52]
In the helper.modalTransitioner() method, this code block never executes because el is not available in !$A.util.isEmpty(el).

`if(!$A.util.isEmpty(el) && el.id == params.targetEl){
    if(!showModal){
        component.set(afterEventAttribute, showModal);
    }
    afterEvent.fire();
    targetEl.removeEventListener('transitionend', transitionListener);
}`

Workaround is to remove the check on el in the first half of the expression.
if (el.id == params.targetEl) {  .... }

**Comment by burhan7** [comment]
Thanks @rueni.

**Comment by matejp84** [comment]
I'm getting exception in Chrome in that line if(!$A.util.isEmpty(el) when modal is opened.

**Comment by matejp84** [comment]
Fixed by downgrading API version back to 38.
