### ISSUE TITLE
need help with sfdx-oss-manifest

### ISSUE THREAD

**Issue by siddharatha** [appiphony/Strike-Components#53]
Hi,
I would like to contribute to these components and am struggling with some basic setup especially with the sfdx-oss-manifest.json as the documentation seems to have changed quite a bit for the plugin and am not sure how to make changes in a dx setup org and contribute in parallel to these components.

And also any guidelines we need to follow for contributing to these components would be great.

Thanks,
Sid

**Comment by mikeblazek** [comment]
For documentation on the SFDX-OSS plugin you can see:  https://github.com/wadewegner/sfdx-oss-plugin

As for contributing to Strike-Components you should not have to do anything to the manifest file, as this just points to the folders that need to be pulled in with the SFDX-OSS Plugin.  This is not required for using Strike, its just a hook into another tool.

As for guidelines on contributing, if you would like to see a feature or fix an issue we would be happy to look at a pull request.   If it is a complete component we would evaluate it and potentially pull it into the library.
