### ISSUE TITLE
Update components to be lightning linter compliant

### ISSUE THREAD

**Issue by dsharrison** [appiphony/Strike-Components#59]
We use the lightning linter from the [salesforce cli](https://www.npmjs.com/package/salesforce-lightning-cli) as part of our CI. We are currently excluding the strike components from our lint task because they are not compliant. It would be great to update them to address the linter errors so that we don't have to exclude them and can properly lint any changes we make to them. I would be happy to open a PR to address this, just let me know.

I am going to be opening an additional enhancement request for some gulp tasks in this repo but I think that supporting `lightning:lint` as a gulp task would be a natural extension of this.

**Comment by daneowens3** [comment]
all components should be linter compliant come next release
