### ISSUE TITLE
Unable to install strike_Carousel: no event named 'fiddle_evt_navigate'

### ISSUE THREAD

**Issue by DouglasCAyers** [appiphony/Strike-Components#60]
Great set of components here, thank you!

Running into issue when trying to install the [strike_Carousel](http://www.lightningstrike.io/#!/strikeCarousel) component, it fails because no event exists with name [fiddle_evt_navigate](https://github.com/appiphony/Strike-Components/blob/master/aura/strike_carousel/strike_carousel.cmp#L11)

Is this perhaps a typo or is the repository missing the event?

I'm installing via clone the repository into my project then trying to deploy from my IDE.

Thanks!

**Comment by DouglasCAyers** [comment]
Removing [line 11](https://github.com/appiphony/Strike-Components/blob/master/aura/strike_carousel/strike_carousel.cmp#L11) fixes the issue and I can install fine. So maybe it's not necessary?

> <aura:registerEvent name="navigate" type="c:fiddle_evt_navigate"/>

**Comment by burhan7** [comment]
@DouglasCAyers We're glad you enjoy using strike components.
Thank you for logging this issue. You're right, that's a typo and it'll be fixed in the next release.

Thanks.

**Comment by DouglasCAyers** [comment]
Thanks
