### ISSUE TITLE
Multiselect value attribute not working properly

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#62]
I have found strange behaviour when creating multi select component with value or changing it's value from javascript. If I use attribute value, value is set, but none of selected pills are created. I'm 100% sure, that value exists in dropdown. Same is true for when setting value from javascript ({!"v.value"}.

It only works when using externalValueChange(string) call. Would be nice to be able to set value via attribute on init :)

**Comment by trentchilders** [comment]
You should, indeed, be able to set the value on init. I am able to do that in our testing environment by simply setting `v.value` on the `strike_multiSelectPicklist` component. Per the component's logic, the value will be set at the `doneRendering` stage of the Lightning rendering lifecycle. After that you will need to call the `externalValueChange` method to update the value. Keep in mind that the `value` attribute for this component is a semi-colon separated string that coincides with the `value` attributes of the corresponding `strike_option` components. I hope this helps.

**Comment by matejp84** [comment]
Yes, but value isn't set on init, when assigning value inside html like this:
`<c:strike_multiSelectPicklist label="Report Category (Send reports by Email)" value="{!v.selectedEmployee.employee.Report_category__c}">
                            <aura:iteration items="{!v.report_category}" var="rc">
                                <c:strike_option label="{!rc.label}" value="{!rc.id}"/>
                            </aura:iteration>
                        </c:strike_multiSelectPicklist>`

value is set behind, but no pills are selected.

**Comment by trentchilders** [comment]
So, I used your code above as a template and implemented it like this:
```
<aura:attribute name="strikeOptions" type="Object[]"/>
	<aura:attribute name="initialValue" type="String"/>

	<aura:handler name="init" value="{!this}" action="{!c.onInit}"/>

	<c:strike_multiSelectPicklist label="Report Category (Send reports by Email)" value="{!v.initialValue}"> 
		<aura:iteration items="{!v.strikeOptions}" var="rc"> 
			<c:strike_option label="{!rc.label}" value="{!rc.id}"/> 
		</aura:iteration> 
	</c:strike_multiSelectPicklist>
```
Controller:
```
onInit : function(component, event, helper) {
    	var strikeOptionValues = [
    	{
    		label: 'lable1',
    		id: '1'
    	},
    	{
    		label: 'label2',
    		id: '2'
    	},
    	{
    		label: 'label3',
    		id: '3'
    	}
    	];
    	component.set('v.strikeOptions', strikeOptionValues);
    	component.set('v.initialValue', '2');
    }
```

And it initialized it as expected on init:
<img width="1093" alt="screen shot 2017-08-09 at 9 53 35 am" src="https://user-images.githubusercontent.com/6664350/29128159-ad7dcc28-7ce8-11e7-88e3-b86c095eee12.png">

So, I'm not sure where yours is failing. Are you using the most up to date version of the component? If so, I guess I would need to see what is in your `{!v.selectedEmployee.employee.Report_category__c}` and `{!v.report_category}`

**Comment by matejp84** [comment]
Here are the values (logged from js console):

Report_category__c: "SI;HR;BA"

report_category: Array (5)
0 {id: "KMAG", label: "KMAG"}
1 {id: "SI", label: "SI"}
2 {id: "HR", label: "HR"}
3 {id: "BA", label: "BA"}
4 {id: "RS", label: "RS"}

I fixed the issue to fill with calling externalValueChange after component finishes loading for now.

**Comment by trentchilders** [comment]
I'm not sure why it isn't working for you but as long as your work around is working I guess just keep at it.
