### ISSUE TITLE
How to implement a lazy-loading on Multiselect Picklist

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#63]
I have a page with potentially many of those picklist so I don't want to preload all of the options on init.

Is there any way to just load the options when the user focuses or when you internally set menuOpen  to true? Seems like you don't expose that?

**Comment by dsharrison** [comment]
While no event is exposed think you might be able to achieve this today by surrounding your `<c:strike_multiSelectPicklist />` with a `<div />` and attach event listeners for `onmousedown` and `onkeyup` to handle a click into the div as well as a tab focus in. This would look like:

```
<div onmousedown="{!c.loadOptions}" onkeyup="{!c.loadOptions}">
        <c:strike_multiSelectPicklist
            label="Multi Select Label"
            errorMessage="Invalid input">
            {!v.options}
    </c:strike_multiSelectPicklist>
</div>
```

I tried this in my org with just a `console.log()` in the controller function and it fired as expected.

**Comment by up2go-rsoesemann** [comment]
```
 <aura:iteration items="{!v.attributes}" var="attribute">
                        <c:section title="{!attribute.label + ' (' + attribute.selectCount +')'}" onMouseDown="{!c.action}">
                            <c:strike_multiSelectPicklist label="" placeholder="{!attribute.label + ' - Select values'}" value="{!attribute.selected}" onchange="{!c.filterChange}">
                                <aura:iteration items="{!attribute.values}" var="value">
                                	<c:strike_option label="{!value}" value="{!value}"/>
                                </aura:iteration>
                            </c:strike_multiSelectPicklist>
                        </c:section>
```
I already wrap them with a custom component. Perfec place for this action. But how would I tell my action what of the n lists it should populate. How can I pass parameters?

**Comment by dsharrison** [comment]
You cannot pass parameters to a Lightning Component controller action. Instead, you will want to look at the `event` argument in your controller action to determine the source. There are a number of [options](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_cb_which_button_pressed.htm) here but I find the easiest to use is an [HTML5 data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes). Note that you cannot set data attributes on many aura components so you may instead need to use a standard `<div data-id="{!attribute.id}" />` to wrap your multi-select and do the event detection. You can then access the value in the data attribute by using `event.target.dataset.id`.

**Comment by up2go-rsoesemann** [comment]
thank you so much for helping out!

**Comment by up2go-rsoesemann** [comment]
The event listener in the surrounding div seems to stop the event from being also handled by the embedded strike component. At least it doesn't open the lookup anymore.
