### ISSUE TITLE
strike_dataGrid sortable option for type COMPONENT

### ISSUE THREAD

**Issue by siddharatha** [appiphony/Strike-Components#67]
The sort option for strike_dataGrid for type COMPONENT would be great.
if we could pass a different value other than the component body it would be really helpful to sort.

**Comment by kevinberonilla** [comment]
Hi @siddharatha,

Good news is we're already in the middle of implementing this feature and it should be ready by the next release! The way we've approached it is by adding a new property (alongside the existing `type` and `attributes`) called `sortValue` that accepts a string.

**Comment by daneowens3** [comment]
expect this feature in our next release
