### ISSUE TITLE
multiselectpicklist handleNotifyParent error on VF page

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#68]
After adding my component which includes multiple multiselectpicklist components on VF page (customer cannot switch to LEX yet), I'm getting this error written at the bottom of the page, and multiselect picklists doesn't show any dropdown:

This page has an error. You might just need to refresh it. Action failed: c:strike_multiSelectPicklist$controller$handleNotifyParent [null is not an object (evaluating 'component.find('inputField').getElement().value = ''')] Failing descriptor: {c:strike_multiSelectPicklist$controller$handleNotifyParent}

**Comment by daneowens3** [comment]
this error doesn't show on lightningstrike.io (a VF page). could you give me more details about this error or what you have attempted to do as i cant reproduce this.
