### ISSUE TITLE
Component Error when there is only one column in dataTable

### ISSUE THREAD

**Issue by mbowen000** [appiphony/Strike-Components#70]
When creating a table with one column and the type is 'COMPONENT' (I know, obscure) there is an error in the strikeRow when dynamically generating the field component:

```js
$A.createComponent(type, attributes, function(newCmp, status, errorMessage) {
					if (status === 'SUCCESS') {
						var valueOutput = component.find('value-output')[index];
                        valueOutput.set('v.body', newCmp);
                    }
				});
```
The failure is on the `component.find('value-output')[index];` because the `find()` returns a single-element rather than an array. A check with `$A.util.isArray()` should fix it right up.

I can work on a PR if I get a chance.

Thanks!

**Comment by daneowens3** [comment]
@mbowen000 can you show me how you are trying to implement this

**Comment by daneowens3** [comment]
@mbowen000 i was able to recreate your issue and solve it with your fix. i will add this to our next release thanks!
