### ISSUE TITLE
Issue with dataGrid when dynamically removing a row when size = 1

### ISSUE THREAD

**Issue by mbowen000** [appiphony/Strike-Components#72]
I encountered an issue when I was attempting to delete rows from the dataGrid. I have the component set to correctly remove rows when a ui:button is clicked on any of the rows. It works fine, however when I've removed all but 1 of the rows, clicking delete does not remove the last row. I found that there is a bug where the `v.body` attribute is only getting set in the callback of the createRowCallback. Thus, if there are no rows to render (rows.size is 0) it won't call `.set('v.body', [])` 

Here is the code that is causing: 
```js
                var createRowCallback = function(newCmp, status, errorMessage){
			if(status === 'SUCCESS'){
				body.push(newCmp);
				component.set('v.body', body);
				component.set('v.showTable', true);
			}
		}

			formattedData.rows.forEach(function(row){
				$A.createComponent(
					"c:strike_row",
					{
						"fields": row.fields
					},
					createRowCallback
				)
			});

			helper.sortTable(component, null, helper);
		
```

I'll shoot a PR over that has a fix in it if you care to use it.

Another thing I noticed is that you are calling `$A.createComponent()` for each row. It would probably be faster to utilize the `$A.createComponents()` method and batch create all the rows.

Thanks,
Mike

**Comment by daneowens3** [comment]
@mbowen000 could you show us how you're implementing the ui button?
