### ISSUE TITLE
radio group click event handler throws error when removing event handler

### ISSUE THREAD

**Issue by pauljrooney** [appiphony/Strike-Components#75]
When attempting to implement the strike radio group component example on the lightningstrike.io website, I got an error when the component loaded (running Salesforce Summer '17 with Locker Service enabled):

```
Uncaught afterRender threw an error in 'markup://c:strike_radioGroup' [el.removeHandler is not a function]
throws at https://xxxxxx.lightning.force.com/auraFW/javascript/ra1ulv_rPNMd9ZOOtLxgew/aura_prod.js:8:15

Object.updateEl()@components/c/strike_radioGroup.js:54:16
Object.<anonymous>()@components/c/strike_radioGroup.js:35:24
Object.selectRadioButtonFromValue()@components/c/strike_radioGroup.js:27:14
afterRender()@components/c/strike_radioGroup.js:74:13
```

It looks like the call to removeHandler on strike_radioGroupHelper.js:37 fails, as there is no removeHandler method on elements. Commenting out that line resolves the issue (not sure if it introduces a different issue, however). I'm assuming the check for addHandler is for backwards compatibility reasons since that method is deprecated, but maybe that whole if-block can be removed?

**Comment by daneowens3** [comment]
Hi Paul,

It looks like you can comment out that line or remove that part all together without issue. I wasn't able to reproduce this error loading the component but removing those lines had no impact.
