### ISSUE TITLE
Issue while Deploying strike_datePicker 

### ISSUE THREAD

**Issue by manjot0074** [appiphony/Strike-Components#77]
I was installing strike components first time. So on installing strike_datepicker .cmp file for strike_input and strike_datepicker was not getting created. On debugging i found that strike_svg is required for strike_input so i installed strike_svg first and then installed strike_datepicker.

Steps to reproduce:-
1:- an org where no strike component is deployed.
2:- then use strike install strike_datepicker to deploy code to org.
3:- you will get an error of FIELD_INTEGRITY.

**Comment by trentchilders** [comment]
Thanks so much for identifying this issue. I'm going to remove the `strike_svg` reference completely and add lightning:icon instead in the next release. Cheers!
