### ISSUE TITLE
let user deselect in select component

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#78]
Is there any option to add clear value or something to let user clear selection if select is already filled in or user made mistake selecting in certain select?  
Right now user can select one option, but cannot empty select to empty.

**Comment by trentchilders** [comment]
Hi @matejp84  You can just set the value to null from outside of the component. That should return the component to its default state.
```
<c:strike_select aura:id="selectInput">
        <aura:iteration items="{!v.strikeOptions}" var="so">
            <c:strike_option label="{!so.label}" value="{!so.value}"/>
        </aura:iteration>
    </c:strike_select>
    <button onclick="{!c.clearValue}">Click</button>
```
Controller
```
clearValue: function(component,event,helper){
        var select = component.find('selectInput');
        select.set('v.value', null);
    }
```

**Comment by jlorca** [comment]
Hello @trentchilders what if you want to reset the selected values of strike_multiSelectPicklist from outside of the component?

**Comment by trentchilders** [comment]
@matejp84 there is currently no option for that but you can add a button that sets the value to null

**Comment by trentchilders** [comment]
@jlorca for multi select pick list you will need to use the 'externalValueChange' method. Please see the documentation here http://www.lightningstrike.io/#!/strikeMultiSelectPicklist
