### ISSUE TITLE
strike_wizard in Simple displayMode click event incorrect parameters

### ISSUE THREAD

**Issue by chadevanssf** [appiphony/Strike-Components#79]
When leveraging the click event in displayMode="Simple", the event does not populate the results correctly. In the function "renderSimpleMode", you can see the for loop should not be setting the results.current unless it finds the chevron the user has just clicked on. The single line below should not exist so that the correct "current" chevron is passed to the event.

for (var i = 0; i < chevrons.length; i++) {
            var chevron = chevrons[i];
            chevron.class = '';
            if (i == targetChevron) {
                chevron.active = true;
                chevron.current = false;
                results.current = i || 0;
                chevron.class += 'slds-is-active slds-is-incomplete';
            } else {
                chevron.active = false;
                chevron.current = false;
                results.current = i || 0; // REMOVE THIS LINE!
                chevron.class += 'slds-is-incomplete';
            }
        }

**Comment by daneowens3** [comment]
i'm not seeing this happen when i test this. could you be more specific as to what is happening and what your issue is because i'm always getting the correct current chevron in the event.
