### ISSUE TITLE
Make Distributable Through Managed Package

### ISSUE THREAD

**Issue by lfreeland** [appiphony/Strike-Components#82]
The strike components are great. It would be nice if they were packaged via a managed package so they could be more easily distributed, especially with new releases. It would make upgrading easier too.

**Comment by ejwill** [comment]
@lfreeland I don't see a great benefit it making a managed package.  By having a managed package I would no longer be able to make changes to the code in my org.  There are a few other reasons that I would advocate against distributing Strike through a managed package but that is the main one.  If, you are looking for an easier way to deploy Strike it might make sense to add [Andrew Fawcett's Salesforce Github deploy button](https://github.com/afawcett/githubsfdeploy) to the repo.

**Comment by burhan7** [comment]
Thank you @lfreeland for submitting your idea. You can easily install and update strike components using [Strike CLI](http://www.lightningstrike.io/#!/gettingStarted)
Right now, we are not planning to package strike components.
