### ISSUE TITLE
Support sticky headers in strike_dataGriid

### ISSUE THREAD

**Issue by siddharatha** [appiphony/Strike-Components#83]
It would be great to have support for sticky headers and scrollable content for the table.
We are playing with different css combinations, but something at the component level would be a huge benefit.

**Comment by mikeblazek** [comment]
@siddharatha we do not plan on adding things such as sticky headers and scrollable content to the table.   We plan to only support what is defined in the Salesforce Lightning Design System.  You can find those guidelines here:  https://www.lightningdesignsystem.com/components/data-tables
