### ISSUE TITLE
chart component not working inside modal component

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#84]
I'm trying to make strike_chart inside strike_modal, but when I open modal chart isn't rendered, only x-axis label and border, but no chart.
Data is provided, as I have same line of code outside of modal and chart works perfectly.

**Comment by burhan7** [comment]
@matejp84 Thank you for logging this. 

I tried to reproduce this one, but was unable to do it. 

<img width="670" alt="strike chart inside strike modal" src="https://user-images.githubusercontent.com/7839963/31234746-4e76863a-a9b5-11e7-9d12-c3f4874d5d5b.png">


Maybe the way you are passing data to the component is causing the issue on your side.

Please try doing it like this:
• Define an attribute for data:
<aura:attribute name="data" type="Map[]" default='[{"x":"Kosovo","y":3256},{"x":"Germany","y":2119},{"x":"Canada","y":1269}]' /> 

• Pass data attribute to the component:
      <c:strike_chart
                type="bar"
                data="{!v.data}"
                title="Average Score"
                leftSubtitle="Score Period"
                rightSubtitle="5 Oct 2017"
                orientation="vertical"
                xAxisLabel="Country"
                yAxisLabel="Score"
                thresholdLabel="Threshold"
                thresholdValue="2133" />


Let us know if you are still having issues with it.

**Comment by matejp84** [comment]
Actually I discovered, that chart was on modal, but it's width and height was 0px, 0px, so it was never rendered. 
Can you share your html you used to embed chart into modal?

**Comment by burhan7** [comment]
@matejp84 Here is complete example:

`<aura:attribute name="showModal" type="Boolean" default="{!true}" description="Determines whether modal is displayed"/>`
`<aura:attribute name="data" type="Map[]" default='[{"x":"Kosovo","y":3256},{"x":"Germany","y":2119},{"x":"Canada","y":1269}]' />`

	<c:strike_modal aura:id="chartModal" title="Data" showModal="{!v.showModal}">
		<c:strike_chart 
			type="bar" 
			data="{!v.data}"
			title="Average Score" 
			leftSubtitle="Score Period" 
			rightSubtitle="6 Oct 2017" 
			orientation="vertical" 
			xAxisLabel="Country" 
			yAxisLabel="Score" 
			thresholdLabel="Threshold"
			thresholdValue="2133" />

		<aura:set attribute="footerButtons">
        	        <lightning:button variant="brand" label="Got It"/>
		</aura:set>
	</c:strike_modal>


Please let us know if you are still having issues with it.
