### ISSUE TITLE
strike_carousel not rendering with aura:iteration

### ISSUE THREAD

**Issue by dschultz-mo** [appiphony/Strike-Components#85]
I am attempting to use an iterator to render cards within a carousel.  The carousel works fine with static cards, but when I put a card tag within an iterator, the entire carousel fails to render.

```
    <c:strike_carousel
                       iconName="standard:carousel"
                       title="Cards"
                       showTotal="true">
        
        <aura:iteration items="{!v.products}" var="product">
            <c:strike_carouselCard
                                   imgSrc="https://placeimg.com/300/300/tech"
                                   imgHref="http://appiphony.com"
                                   title="{!product.Name}"
                                   titleHref="http://appiphony.com"
                                   buttonLabel="Get Started"
                                   buttonHref="http://www.appiphony.com"/>
        </aura:iteration>
    </c:strike_carousel>
```

Looking at the carousel controller, it appears there is code within onInit that should handle this, but the 'children' value is empty.  get('v.body') on an aura:iteration returns nothing.

```
            if (el.toString().match(/aura:iteration/)) {
                console.log('This is an iteration ' + el);
                var children = el.get('v.body');
                console.log('...with children ' + children);
        		cards = children;
```

console:
This is an iteration SecureComponentRef: markup://aura:iteration {7:0}{ key: {"namespace":"c"} }
...with children 

This appears to happen on both API version 39 and 40.
Could this be related to https://salesforce.stackexchange.com/questions/146351/gack-when-using-auraiteration-and-indexvar?  I attempted to add various html markup but still see no children in the body of aura:iteration.

**Comment by burhan7** [comment]
Thanks @dschultz-mo for logging this issue. We'll take a look at this and will keep you posted.

**Comment by burhan7** [comment]
@dschultz-mo I just try reproducing this issue, but was unable to do it.
Maybe the way you are passing data to the component is causing the issue on your side.

<img width="810" alt="strike carousel" src="https://user-images.githubusercontent.com/7839963/31238403-75d6c712-a9bf-11e7-80cf-348eb2cda619.png">


Here is what I did:
• Defined a products attribute:
        `<aura:attribute name="products" type="Map[]" description="Cards data"/>`

• Set products attributes from the controller/helper:
        `var products = [
            {
                Name: 'Card Title 1',
            },
            {
                Name: 'Card Title 2',
            },
            {
                Name: 'Card Title 3',
            },
            {
                Name: 'Card Title 4',
            }
        ];
        component.set('v.products', products);`


• Passed data attribute to the component:
`       <aura:if isTrue="{!not(empty(v.products))}">
		<c:strike_carousel
            iconName="standard:carousel"
            title="Cards"
            showTotal="true">        
<aura:iteration items="{!v.products}" var="product">
	            <c:strike_carouselCard
	                imgSrc="https://placeimg.com/300/300/tech"
	                imgHref="http://appiphony.com"
	                title="{!product.Name}"
	                titleHref="http://appiphony.com"
	                buttonLabel="Get Started"
	                buttonHref="http://www.appiphony.com"/>
	        </aura:iteration>
	    </c:strike_carousel>
	</aura:if>`


Please let us know if you still have any issue.

**Comment by dschultz-mo** [comment]
Ok, this helped me diagnose this further.

The problem is that my products attribute has not yet been populated by the
call to the server side controller when the carousel controller onInit
runs.  So, there is no aura:iteration in the body of the strike_carousel
yet and therefore no child cards are created.  The magic required to make
it run is the <aura:if isTrue="{!not(empty(v.products))}"> wrapper around
the strike_carousel tag.  That causes the onInit code to be delayed until
the body has been built.

Thanks for your assistance.


Regards,

Dennis Schultz
Principal Solution Engineer - Platform | Salesforce
Mobile: 314-265-7311
dschultz@salesforce.com


<http://smart.salesforce.com/sig/dschultz//us_mb_kb/default/link.html>

**Comment by burhan7** [comment]
@dschultz-mo Thanks for letting us know what the issue was. We're glad we could assist you.
We'll close this issue now.

Best regards,
Burhan Islami
