### ISSUE TITLE
Strike Radio Group - Content inside of Radio Option not closing after selecting a new Radio Option, and then not reopening 

### ISSUE THREAD

**Issue by justinAppiphony** [appiphony/Strike-Components#90]
Hi,

I brought the default live code from the fiddler page for Strike Radio Group to a Flexipage/Lightning Record page by placing it inside a wrapper. It appears on the page just fine, however when I switch between radio options, it seems as if the content inside is not closing upon clicking a new radio option, and when it does, navigating back to the radio option with content inside does not open.

Walk-through -
1) Enter code in developer console

<aura:component implements="force:appHostable,flexipage:availableForAllPageTypes" access="global">
	<c:strike_radioGroup
    value="radio-option-2"
    label="Radio Group Label">
    <c:strike_input label="Radio Option 1" value="radio-option-1"/>
    <c:strike_radioGroupContent
	showWhenValueEquals="radio-option-1">
	<aura:set attribute="content">
	    <lightning:select 
		name="Select Name"
		label="Select label"
		value="option-1"
		variant="standard">
		<option value="option-1">Option 1</option>
		<option value="option-2">Option 2</option>
		<option value="option-3">Option 3</option>
	    </lightning:select>
	</aura:set>
    </c:strike_radioGroupContent>
    <c:strike_input label="Radio Option 2" value="radio-option-2"/>
    <c:strike_radioGroupContent
	showWhenValueEquals="radio-option-2">
	<aura:set attribute="content">
	    <lightning:input 
		name="Input Name"
		type="checkbox"
		label="Checked">
	    </lightning:input>
	</aura:set>
    </c:strike_radioGroupContent>
    <c:strike_input label="Radio Option 3" value="radio-option-3"/>
</c:strike_radioGroup>
</aura:component>

2) Navigate back to the Lightning page and refresh page
![image](https://user-images.githubusercontent.com/882708/31095413-611ef08a-a77e-11e7-8f07-3060cac332da.png)

3) Select Option 1 and note the content inside (this will stay open when selecting a different radio option in the next step
![image](https://user-images.githubusercontent.com/882708/31095468-8919284e-a77e-11e7-8d9e-6bfe4acbf9e0.png)

4) Select Radio Option 2 - The content inside of Radio Option 1 stays open
![image](https://user-images.githubusercontent.com/882708/31095514-b685bad6-a77e-11e7-9b3a-81e6b77155a4.png)

5) Select Radio Option 3 - Now Radio Option 1 content closes
![image](https://user-images.githubusercontent.com/882708/31095888-f7411dd0-a77f-11e7-837f-15a55e271616.png)

6) Note that upon reselecting Radio Option 1 again, the content inside does not open
![image](https://user-images.githubusercontent.com/882708/31095801-a9bdd0da-a77f-11e7-90a7-17d5cd857673.png)

**Comment by daneowens3** [comment]
I was able to alleviate this issue by calling "selectRadioButtonFromValue" from "handleClickRadio" as "selectRadioButtonFromValue" was only being called once after render.

**Comment by justinAppiphony** [comment]
Thank you @daneowens3 !

**Comment by daneowens3** [comment]
This has been addressed and should be resolved next release.
