### ISSUE TITLE
Strike Select - doneRendering needs to check for v.value is present

### ISSUE THREAD

**Issue by chewy2** [appiphony/Strike-Components#92]
The doneRendering code needs to be moved to an afterRender in the renderer. The doneRender code only needs to be ran once, but its currently running infinite times and causing infinite loops under certain conditions.

**Comment by chewy2** [comment]
It appears we need to use the doneRendering event to handle the addition of options through a callback. In this case we need to also make sure that the doneRender checks to see if there is a v.value as well as a v.valueLabel otherwise when a component gets destroyed its stuck in an infinite loop due to not having a label, but theres no value to set a label.

**Comment by daneowens3** [comment]
expect this to be resolved in our next release, added the check for v.value.

**Comment by cnaccio** [comment]
@chewy2 I think I ran into this issue today with version 0.9.0 of the select component. I started receiving the error below in certain circumstances. Is this the same thing?

![image](https://user-images.githubusercontent.com/8041783/34450365-bc9aba6e-eccc-11e7-9dcd-c760926e5982.png)


Here's the specific offending code/function in file strike_selectHelper; more specifically this line **_component.get('v.body').forEach(function(child) {_**

```
    getChildOptions: function(component, event, helper) {
        var options = [];

        component.get('v.body').forEach(function(child) {
            if ($A.util.isUndefined(child.select)) {

                var childOptions = helper.getChildOptions(child, event, helper);

                options = options.concat(childOptions);
            } else {
                options.push(child);
            }
        });

        return options;
    }
```
