### ISSUE TITLE
Strike:select forEach error

### ISSUE THREAD

**Issue by seankearneycm** [appiphony/Strike-Components#95]
I noticed a similar issue was closed 2 months ago as a bug.  Is there a known solution for this error?

![strikeerror](https://user-images.githubusercontent.com/26722909/31235500-4f503fb8-a9b7-11e7-9d79-6222c45ba1ca.jpeg)

**Comment by daneowens3** [comment]
Hello Sean, 

Im attempting to reproduce your issue, but i'm having some trouble doing so. Could you be specific as to what you were attempting to do or when the error is thrown? "getChildOptions" is called in may places and it be helpful to know where exactly you are having trouble.

**Comment by seankearneycm** [comment]
Thanks for the reply.

The component seemed to work fine as intended except, if we navigated from this record context to a different context.  Any time we navigated away from the component or came back it would throw the error.  Though, the error didn’t throw every time, I was assuming it was based on the rendering cycle and the value was null when attempting to render.  We tried some workarounds but nothing seemed to work.  Does this make sense?

Thanks


Sean Kearney
CROSSMARK® | UX Design | 5100 Legacy Drive | Plano, TX, 75024 | sean.kearney@crossmark.com<mailto:sean.kearney@crossmark.com> | C: (972) 339-0423

This message, including any attachments, is confidential and/or proprietary to CROSSMARK® and its affiliated companies and should be read or retained only by the intended recipient. If you have received it in error, please notify the sender immediately and delete the original message.

**Comment by daneowens3** [comment]
Sean, i am still unable to reproduce this error. Did you make any modifications to the code?

**Comment by seankearneycm** [comment]
No we didn’t touch the strike components.

I’ll update with the code we used to implement as well
